{
	"error":0,
	"errorSummary":"",
	"errorDescription":"",
	"errorIsWarning":false,
	"silentError":0,
	"payload":{
		"main":{
			"viewMain":{
				"form":"apps",
				"view":"FRMW_APPS01"
			}
		},
		"forms":{
			"apps":{
				"name":"apps",
				"views":{
					"FRMW_APPS01":{
						"fields":[
							{
								"name":"appName",
								"type":"string",
								"form":"apps"
							},
							{
								"name":"description",
								"type":"string",
								"form":"apps"
							}
						]
					}
				},
				"fieldforms":[
					{
						"name":"appName",
						"id":"appName",
						"type":"field_alphanumeric"
					},
					{
						"name":"description",
						"id":"description",
						"type":"field_alphanumeric"
					}
				]
			}
		}
	},
	"resource_map":null,
	"css":[],
	"js":[]
}